import { Metadata } from "next";

export const metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution", // Example template
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: '#ff0000', padding: '30px' }}>
          Header
        </header>
        {children}
        <footer style={{
          backgroundColor: '#ab1a90',
          padding: '30px'
        }}>
          <p> Footer </p>
        </footer>
      </body>
    </html>
  );
}