export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:'#ff0000',padding:'30px'}}>
          Header
        </header>
        {children}
        <footer style={{
          backgroundColor:'#ab1a90',
          padding:'30px'
        }}>
          <p> Footer </p>
        </footer>
        </body>
    </html>
  )
}
